
spring:
  application:
    ####注册中心应用名称
    name:  api-order-impl
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
    ###因为该应用为注册中心，不会注册自己
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true
###开启Hystrix断路器 
feign:
  hystrix:
    enabled: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
      
server:
  port: 8882

#### hystrix禁止服务超时时间
hystrix:  
 command: 
   default: 
     execution: 
       timeout: 
         enabled: true
