###注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 80
###网关名称
spring:
  application:
    name: service-zuul
#### 配置网关反向代理    
zuul:
  routes:
    api-member:
     ### 以 /api-/访问转发到会员服务
      path: /api-/**
      serviceId: app-member
    api-order:
        ### 以 /api-/访问转发到订单服务
      path: /api-/**
      serviceId: app-order
management:
  endpoints:
    web:
      exposure:
        include: "*"
ribbon: 
  eureka: 
    enabled: true
